const data={
    products:[
    {
     _id:'1',
     image:'/resimler/resim1.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Her Yönüyle GraphQL ve Apollo',
     yorum:12,
     price:79.99,
     description:'GraphQL ve Apollo ile Node.JS  Express ve MongoDB Üzerinde Real-Time API Geliştirin',
     icerikbir:'Modern web uygulamalarını tek başınıza geliştirebileceksiniz.',
     icerikiki:'Node JS ve React ile yetkilendirme işlemlerini yapabileceksiniz.',
     icerikuc:'Scalable dosya ve dizin yapısı kurgulayabileceksiniz.',
     icerikdort:'GraphQL ve Apollo ile Real-Time çalışan API geliştirebileceksiniz.',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'Node JS GraphQL Apollo MongoDB ve Reactı aynı proje üzerinde kullanabileceksiniz.',
     icindekilerbir:'9,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'1 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Temel seviye JavaScript ve React bilgisi.',
     hakimiyet:'Express ile GraphQL kurulumu GraphQL Schema Root Query Resolver GraphQLID GraphQL List GraphQLNonNull Relations Custom Type Apollo Client React Apollo Module Refetch QUERY MUTATION GraphiQL'
    },
   {
     _id:'2',
     image:'/resimler/resim2.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan HTML5 ve CSS3 Kursu',
     yorum:19,
     price:64.99,
     description:'Modern teknik ve teknolojilerle frontend dünyasına sağlam bir temel atın',
     icerikbir:'Frontend dünyasında çalışmak ve projeler geliştirmek isteyen',
     icerikiki:'React Vue Angular gibi frameworklerde projeler yapmak isteyen',
     icerikuc:'Vanilla JS ile oluşturduğu mantığı daha güzel bir arayüzle kullanıcılara sunmak isteyen',
     icerikdort:'Popüler css çözümlerini öğrenip, resposive web sitesi yapmak isteyen herkes bu kursa katılabilir',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'Node JS GraphQL Apollo MongoDB ve Reactı aynı proje üzerinde kullanabileceksiniz.',
     icindekilerbir:'17,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'4 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Bu kursa katılmak için herhangi bir ön koşul yoktur Tüm dersler sıfırdan başlanacak ve ileri seviyeye doğru gidilecektir.',
     hakimiyet:'HTML ve CSS frontend geliştiricisi olmak isteyen birinin mutlaka herşeyiyle bilmesi gerektiği konulardır CSS3 ü yeni özellikleriyle öğrenip hızlı bir şekilde responsive tasarımlar yapabilirsiniz.Bu kursta html ve cssde bilmeniz gereken tüm konular detaylı anlatım ve örneklerle anlatılmıştır.Flexbox grid kavramlarını en iyi şekilde öğrenip web sitelerinizi kolayca yapabilirsiniz.'
    },
   {
     _id:'3',
     image:'/resimler/resim3.jpg',
     name:'Berkant Kaya',
     brand:'React JS Uygulamalı React JS Eğitimi',
     yorum:22,
     price:89.99,
     description:'React js - React Component - React State - React LifeCycle - React Router - React JS Projeleri -React JS',
     icerikbir:'Modern web uygulamalarını tek başınıza geliştirebileceksiniz.',
     icerikiki: 'React ile yetkilendirme işlemlerini yapabileceksiniz.',
     icerikuc:'Scalable dosya ve dizin yapısı kurgulayabileceksiniz.',
     icerikdort:'React Js Öğrenmek İsteyen Öğrenciler',
     icerikbes:'Uygulamalı React Eğitimi Almak İsteyen Öğrenciler',
     icerikalti:'Node JS GraphQL Apollo MongoDB ve Reactı aynı proje üzerinde kullanabileceksiniz.',
     icindekilerbir:'15,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'11 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Html Css Javascript Ön Bilgisi',
     hakimiyet:'React Js yi öğrenmek steyenler Resolver GraphQLID GraphQLList Bilgisi olup da proje yapamayan öğrenciler React Apollo Module Refetch QUERY MUTATION GraphiQL'
    },
   {
     _id:'4',
     image:'/resimler/resim4.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Git Kullanımı : Versiyon Kontrolünün Gücü',
     yorum:32,
     price:29.99,
     description:'A-Z Git kullanimi ve proje gelistirmesurecini kisaltma ve verimini arttirma yontemleri',
     icerikbir:'Git versiyon kontrolu sistemini etkin olarak kullanabilecek',
     icerikiki:'Diger versiyon kontrol sistemleri hakkinda bilgisi olacak',
     icerikuc:'Git versiyon kontrolu sistemi sayesinde birden cok gelistirici oldugu durumlarda projede birbirinin kodlarini bozmadan hizlica proje gelistirebilecek',
     icerikdort:'Git ve Github ile nete veri yükleme geliştirebileceksiniz.',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:' Apollo MongoDB ve Reactı aynı proje üzerinde kullanabileceksiniz.',
     icindekilerbir:'1,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'3 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Versiyon kontrolune neden ihtiyaci oldugunu bilmelidir',
     hakimiyet:'Programlamaya ya da giti nerelerde kullanilabileceginize dair fikriniz olmalidir.GraphQLNonNull Relations Custom Type Apollo Client React Apollo Module Refetch QUERY MUTATION GraphiQL'
    },
   {
     _id:'5',
     image:'/resimler/resim5.jpg',
     name:'Berkant Kaya',
     brand:'Bootstrap 4 ile Sıfırdan Harika Web Projeleri Oluşturun',
     yorum:2,
     price:39.99,
     description:'BOOTSTRAP en son sürümünü öğrenerek Facebook Onedio 140Journos gibi BOOTSTRAP 4 premium tasarımlar yapıyoruz.',
     icerikbir:'Sıfırdan yüksek kaliteli Bootstrap 4 temaları ve kullanıcı arayüzleri geliştirmeyi öğreneceksiniz.',
     icerikiki:'Anlamlı HTML5 ve modern CSS 3 tekniklerini öğreneceksiniz.',
     icerikuc:'Web projelerinizde tasarım arama derdinden kurtulacak ve kendi tasarımlarınızı hazırlayıp kullanabileceksiniz.',
     icerikdort:'GraphQL ve Apollo ile Real-Time çalışan API geliştirebileceksiniz.',
     icerikbes:'Onedio Facebook 140Journos gibi sitelerin premium tasarımlarını yapmayı öğreneceksiniz.',
     icerikalti:'Seo Uyumlu Semantik Web Projelerinin püf noktalarını öğreneceksiniz.',
     icindekilerbir:'13,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'6 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Başlangıç seviyesinde bilgisayar kullanmayı bilmek ve öğrenme disiplinine sahip olmak yeterlidir.',
     hakimiyet:'Unutma! Kimse senin dalgalarla nasıl boğuştuğuna bakmaz Gemiyi limana getirip getirmediğine bakar Ben kaptanınız Berkant Kaya olarak bu eğitim serüvenin sonunda gerçekten sana vaad ettiğim ve hayal kurmanı sağladığım her şeyi yapabilmeni sana taahhüt ediyor sadece kursa kayıt oluncaya kadar değil kurs öğrenme süresi boyuncada sana destek olacağım sözünü veriyorum.'
    },
   {
     _id:'6',
     image:'/resimler/resim6.jpg',
     name:'Berkant Kaya',
     brand:'React Native: React Native IOS & Android Uygulama Geliştirme',
     yorum:52,
     price:109.99,
     description:'React Native ile sıfırdan IOS & Android uygulama geliştirin uygulamalı örneklerle React Native master olun fark yaratın',
     icerikbir:'React Native kullanarak native iOS ve Android mobil uygulama yapabileceksiniz',
     icerikiki:'Bilgisayarda Android ve Iphone simülatörü nasıl çalıştırılır',
     icerikuc:'React Native ile şekil vermek ve flexbox sistemini anlayacaksınız',
     icerikdort:'JSX syntax ve açıklamaları',
     icerikbes:'Mac için React Native Kurulumu',
     icerikalti:'Windows için React Native Kurulumu',
     icindekilerbir:'7 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'5 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'JavaScript + HTML + CSS hakkında temel bilgi sahibi olunmalı',
     hakimiyet:'React-Native, React ekibi tarafından piyasaya sürülen ve şu anda hem Android hem de IOS uygulamalar oluşturmak için yaygın bir şekilde kullanılan bir kütüphanedir. IOS ve Android gibi mobil uygulamalar için gerekli olan native geliştiricileri JavaScript ile kullanıcı ara yüzü oluşturmak için kullanılan en iyi kütüphanelerden biri olan React ile birleştirir.'
    },
   {
     _id:'7',
     image:'/resimler/resim7.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Her Yönüyle NestJs + mongoDB',
     yorum:32,
     price:19.99,
     description:'Typescript yazarak en hızlı NodeJs çerçevesi ile tüm operasyonel kurguları içeren modern bir Rest Api oluşturmak',
     icerikbir:'NestJs ile bir rest api oluşturma',
     icerikiki:'Cloudinary üzerinden file upload',
     icerikuc:'CI/CD süreçleri ve heroku ile somutlaştırma',
     icerikdort:'MongoDb ile crud işlemleri',
     icerikbes:'Her büyük projenin gereksinimi olan api arayüzü swagger',
     icerikalti:'Git teknolojisini kullanarak Githuba depolama ve branch sistemi',
     icindekilerbir:'4,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'1 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Temel seviye rest api işleyiş mantığı',
     hakimiyet:'NestJs, güçlü ve talepkar backend sistemleri oluşturmamızı sağlayan tam özellikli bir açık kaynaklı NodeJs framework platformudur.  Module Refetch QUERY MUTATION GraphiQL'
    },
   {
     _id:'8',
     image:'/resimler/resim8.jpg',
     name:'Berkant Kaya',
     brand:'C programlama ve C++ programlama ile Yazılım Geliştirme',
     yorum:12,
     price:79.99,
     description:'C programlama & C++ programlama |C programlama & C++ programlama |C programlama & C++ programlama | ***TEK KURS 2 DİL***',
     icerikbir:'C programlama dilinden yola çıkarak YAZILIM DÜNYASINA DAİR AKLINIZA TAKILAN BÜTÜN SORULARA CEVAP BULACAKSINIZ',
     icerikiki:'C programlama dili ve C++ programlama dillerinin nerelerde kullanıldığını öğreneceksiniz.',
     icerikuc:'C programlama ve C++ programlama dillerinin nasıl kodlandığını öğrenecek ve bunu örneklerle pekiştireceksiniz.',
     icerikdort:'C programlama ve C++ programlama dillerinin mantığını kavrayacaksınız.',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'C programlama dilini sıfırdan ileri seviyeye kusursuzca öğreneceksiniz.',
     icindekilerbir:'43,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'5 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Kursta herhangi bir bilgi birikimine gerek yoktur. Her şeyi yazılıma dair sıfır bilgiye sahip birinin anlayacağı şekilde anlattım.',
     hakimiyet:'C Programlama Dilini ve C++ Programlama dilini adım adım, mantığa dayalı bir şekilde öğreten eğitim setine bir adım uzaktasınız.'
    },
   {
     _id:'9',
     image:'/resimler/resim9.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Zirveye Javascript ve NodeJS Kursu 2020',
     yorum:19,
     price:179.99,
     description:'Sıfırdan tüm detaylarıyla javascript öğrenin ve node js ile kendi sunucunuzu oluşturun',
     icerikbir:'Javascript tüm detaylarıyla öğretilecek',
     icerikiki:'Nodejs ile farklı amaçlarda birden fazla uygulama yapılacak',
     icerikuc:'Scalable dosya ve dizin yapısı kurgulayabileceksiniz.',
     icerikdort:'Yapılan uygulamaların nasıl yayına alınması ile ilgili bilgiler verilecek',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'HTML ve CSS en güncel kavramlarla anlatılacak',
     icindekilerbir:'77 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'7 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Öğrenme isteği, çalışma azmi ve bir bilgisayar yeterli',
     hakimiyet:'Javascript dilini detaylarıyla ve de en güncel haliyle öğreneceksiniz. Bu size pek çok dünyanın kapısını aralayacaktır. Sadece js öğrenip sonrasında Angular, React veya Vue teknolojilerinde kendinizi geliştirebilirsiniz. Sağlam bir js temeliniz varsa bunları öğrenmek oldukça kolay olacaktır.'
    },
   {
     _id:'10',
     image:'/resimler/resim10.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Komple Java Geliştirici Kursu',
     yorum:68,
     price:159.99,
     description:'Android , Web Geliştirme ve daha bir çok alanda kullanılan Java Programlama Dilini öğrenmenin tadını çıkarın.',
     icerikbir:'Nesne Yönelimli Programlamanın tüm konseptlerini iyi bir şekilde öğrenmiş olacaksınız ve uygulamalarınızı bu doğrultuda kolaylıkla yazabileceksiniz',
     icerikiki:'Swing kütüphanesini kullanarak profesyonel masaüstü uygulamaları geliştirebileceksiniz',
     icerikuc:'Java ile 2 Boyutlu ( Örnek : Pong Game ) oyunlar yazabileceksiniz.',
     icerikdort:'Swing ve Mysql Veritabanını kullanarak kurumsal uygulamalar geliştirebileceksiniz.',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'En önemlisi, artık CV nize Javayı ileri seviyede biliyorum yazabileceksiniz.',
     icindekilerbir:'41 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'10 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Temel Programlama Bilgisi Yeterlidir (Sadece Değişkenler Koşullar Döngüler Fonksiyonlar)',
     hakimiyet:'Bu kursta sıfırdan Java ile Nesne Yönelimli Programlamanın tüm konseptlerini öğrenerek Javada hep beraber uzmanlaşmaya çalışacağız ve kurs bitiminde profesyonel Java uygulamaları çıkarabilecek seviyeye geleceğiz. '
    },
   {
     _id:'11',
     image:'/resimler/resim11.jpg',
     name:'Berkant Kaya',
     brand:'Uygulama Geliştirerek C# Öğrenin: A dan Z ye Eğitim Seti',
     yorum:33,
     price:100,
     description:'192 Ders ~ C# programlama mantığını modüler bir müfredat aracılığıyla projeler geliştirerek öğrenin! | C#',
     icerikbir:'Nesne Tabanlı Programlamanın (Object Oriented Programming) inceliklerini',
     icerikiki:'2D oyun altyapılarına adım atmayı',
     icerikuc:'Stok takip sistemleri algoritması kurabilmeyi',
     icerikdort:'Veri tabanı kayıt uygulamaları kontrol edebilmeyi',
     icerikbes:'Otomasyon uygulamaları geliştirebilmeyi',
     icerikalti:'Cari takip fatura ve muhasebe projeleri yazabilmeyi',
     icindekilerbir:'22 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'1 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Önceden öğrenilmiş hiçbir programlama dili bilgisine sahip olmanız gerekmemektedir.',
     hakimiyet:'Pek çok kişi yazılım dünyasına ilk adımı atmak ister ancak nereden başlayacağını bilemez. Bu kapsamlı C# dersim ile sizleri Sıfırdan İleri Seviyeye çıkarmayı hedefleyerek yazılım serüveninizde Türkçe hazırlanmış eğitimler ile size bir parça da olsun katkıda bulunmak en büyük arzum.'
    },
   {
     _id:'12',
     image:'/resimler/resim12.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan Uygulamalı MySQL Eğitimi',
     yorum:43,
     price:29.99,
     description:'MySQL ile beraber SQL Query dilini öğrenmek istiyorsanız; bol bol uygulama içeren bu eğitimi kesinlikle kaçırmamalısınız',
     icerikbir:'Rahatlıkla MySQL ve türevlerini profesyonel olarak kullanabileceklerdir',
     icerikiki:'Veri tabanı konusunda teorik olarak profesyonel bilgiye sahip olacaklar',
     icerikuc:'Scalable dosya ve dizin yapısı kurgulayabileceksiniz.',
     icerikdort:'GraphQL ve Apollo ile Real-Time çalışan API geliştirebileceksiniz.',
     icerikbes:'Optimistic UI ile gelişmiş kullanıcı deneyimleri yaratabileceksiniz.',
     icerikalti:'SQL dilini rahatça kullanabilecekler',
     icindekilerbir:'3 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'7 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'phpMyAdmin, Navicat, MySQL workBench gibi bir veri tabanı yönetim uygulaması',
     hakimiyet:'Bu kursun içerisinde sıfırdan Veri Tabanı, SQL ve MySQL kavramlarına giriş yapıp SQL dilini etkili bir şekilde kullanmaya başlıyoruz.'
    },
   {
     _id:'13',
     image:'/resimler/resim13.jpg',
     name:'Berkant Kaya',
     brand:'Sıfırdan İleri Seviyeye Komple PHP ile Web Geliştirme 2021',
     yorum:47,
     price:69.99,
     description:'PHP Web programlama öğrenerek öğrendiklerimizi uygulayıp PHP ile gerçek bir e-ticaret projesi geliştiriyoruz.(PDO+MySQL)',
     icerikbir:'Web programlamanın temeli HTML dilini kavramış olacaksınız.',
     icerikiki:'Dinamik Web Programlamanın mantığını kavramış olacaksınız.',
     icerikuc:'PHP PDO sınıfının kullanımını kavramış olacaksınız.',
     icerikdort:'PHP programlamayı en sade ve bol örnekli anlatımlarla öğreneceksiniz.',
     icerikbes:'MySQL veritabanında CRUD (Select Insert Update Delete) işlemlerini yapabileceksiniz.',
     icerikalti:'Dinamik scriptlere modül geliştirebileceksiniz.',
     icindekilerbir:'44 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'26 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Öğrencilerin başlangıç seviyesinde bilgisayar kullanmayı bilmeleri ve öğrenme disiplinine sahip olmaları yeterlidir.',
     hakimiyet:'Bu kursa kayıtlı öğrencilerimin yaptığı projeleri berkantkaya.com.tr internet sitemin anasayfasında yer alan bağlantıdan inceleyebilirsiniz.'
    },
   {
     _id:'14',
     image:'/resimler/resim14.jpg',
     name:'Berkant Kaya',
     brand:'Unity C# | Sıfırdan 2D & 3D Oyun Geliştirme Eğitimi',
     yorum:82,
     price:279.99,
     description:'Sıfırdan C# ı ve Unity de oyun geliştirmeyi 6 kapsamlı oyunu adım adım kodlayarak öğreneceğiz! | Game Development',
     icerikbir:'Dünyanın en popüler 5 yazılım dilinden biri olan C# ile sıfırdan kodlayabilmeyi',
     icerikiki:'Popüler 2D ve 3D oyunların nasıl yaratıldığını',
     icerikuc:'Unity’nin arayüzünün nasıl kullanılacağını',
     icerikdort:'Oyun geliştirme algoritmasının nasıl oluşturulduğunu',
     icerikbes:'Nesne yönelimli programlama (OOP) mantığını kavramayı',
     icerikalti:'Node JS GraphQL Apollo MongoDB ve Reactı aynı proje üzerinde kullanabileceksiniz.',
     icindekilerbir:'26,5 saat uzunluğunda hazır video içeriği',
     icindekileriki:'Ömür boyu tam erişim',
     icindekileruc:'Bitirme sertifikası',
     icindekilerdort:'9 makale',
     icindekilerbes:'Mobil ve TV den erişim',
     gereksinim:'Hiçbir programlama bilgisi veya Unity tecrübesine sahip olmanıza gerek yoktur!',
     hakimiyet:'Dünya üzerindeki en büyük oyun stüdyolarının ve bağımsız oyun geliştiricilerin kullandığı endüstri standartlarındaki oyun motoru Unity 3D ile kendi oyun projelerinizi hayata geçirmek sadece sizin elinizde!'
    }
   ]
   }
   export default data;